apiVersion: v1
kind: Service
metadata:
  name: redis-svc-0
  labels:
    app: redis-0
spec:
  type: ClusterIP
  ports:
    - port: {{.TotalCount}}
      targetPort: 6379
      name: client
    - port: 16379
      targetPort: 16379
      name: gossip
  selector:
    app: redis-0
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc-1
  labels:
    app: redis-1
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: client
    - port: 16379
      targetPort: 16379
      name: gossip
  selector:
    app: redis-1
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc-2
  labels:
    app: redis-2
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: client
    - port: 16379
      targetPort: 16379
      name: gossip
  selector:
    app: redis-2
